### ISSUE TITLE
select2 binding handler with ajax implementation

### ISSUE THREAD

**Issue by dyardyGIT** [cruikshj/knockout-select2#2] opened 2015-10-14 17:26 UTC
Uncaught DOMException: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.(…)

I am getting that error on the following line
              allBindings[dataBindingName]($(element).select2("data"));

I get this error when i move (similar to your sample)  var select2Data = ko.observable(); to my viewModel with self.select2Data = ko.observable();

I am not sure how they are different at this point and why moving the declaration of select2Data to the viewmodel would cause this type of error.

Ideas?

**Comment by cruikshj** [comment] 2015-10-14 18:03
That is a very odd error which should not have anything to do with the viewModel property location.  What browser are you using and can you provide some sample code so that I can recreate it.

**Comment by dyardyGIT** [comment] 2015-10-15 12:02
<select multiple="multiple" data-bind="select2Data: SubmissionClient.approverGen, select2: spec"></select>         

    var viewModel;
    var url = '@Model.RootUrl';
    var environment = '@Model.Environment';
    var model = JSON.parse(document.getElementById("model-div").getAttribute("data-json"));
    $(function () {  
        viewModel = new ViewModel(url, environment, model);
        ko.applyBindings(viewModel);
    });

Within my viewmodel i have the following..


var ViewModel = function (url, environment, data) {
    "use strict";

    var self = this;
    self.url = url;
    self.environment = environment;    
    //self.select2Data = ko.observable('');
    ko.mapping.fromJS(data, {}, this);

    //var select2Data = ko.observable();
    // multiple="multiple"
    self.spec = {
        placeholder: "Select...",
        multiple: false,
        minimumInputLength: 3,
        templateResult: function (item) {
            return item.text;            
        },
        templateSelection: function (item) {
            return item.text;            
        },
        escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
        ajax: {
            contentType: 'application/json',
            dataType: 'json',
            delay: 250,
            type: 'POST',
            url: function (params) {
                return jsonUrl; //set elsewhere
            },
            data: function (params) {
                return getData(params.term, 'name');
            },
            processResults: function (data) {
                return {
                    results: $.map(JSON.parse(data), function (item) {
                        return { id: item.Id, text: item.Name, data: item };
                    })
                };
            },
            cache: true
        }
    };
};


With the above code i get this error
Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

The error occurs on line 61
            if (ko.isWriteableObservable(allBindings[dataBindingName])) {
                dataChangeHandler = function () {
                    allBindings[dataBindingName]($(element).select2("data")); //<<<<<HERE
                };
                $(element).on("change", dataChangeHandler);
            }

**Comment by dyardyGIT** [comment] 2015-10-15 12:28
Stepping through (more) today, my observable gets set to an object and it is during the update of the control that i am getting this error (within ko).  Potentially like ko is trying to set a property to an object and it is really looking for a value??

`Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

**Comment by cruikshj** [comment] 2015-10-15 14:10
What is SubmissionClient.approverGen?

I have yet to reproduce the issue.  I suspect the error is being thrown inside `$(element).select2("data")`, when it tries to read the data from the control.  

Does the same error occur in all browsers?

**Comment by dyardyGIT** [comment] 2015-10-15 15:46
Sorry SubmissionClient.approverGen is object/property in my viewmodel (that may have been confusing).
$(element).select2("data") when you console out...shows an [object] with the selected item

When i used $(element).select2("data")[0].id it set the ko property ok but the UI was not updated.  I think the error is all within how the UI gets updated (i.e. the text is not shown in the select2 elemetn after selection)

**Comment by cruikshj** [comment] 2015-10-15 18:30
Keep in mind, select2Data is 'readonly'.  If you set the observable for select2Data, nothing in my binding handler will try to update select2 with that value.  It is only useful for getting a value when set by select2.  This is due to a limitation with select2 itself not supporting 'data' being set, only read.

I am not sure if this is part of your use case, just an FYI.

**Comment by cruikshj** [comment] 2015-10-15 18:50
not sure if this is an issue... but you have two things called `data`.  are you sure the following code is mapping the data you want?

`processResults: function (data) {
            return {
                results: $.map(JSON.parse(data), function (item) {
                    return { id: item.Id, text: item.Name, data: item };
                })
            };
        },`

**Comment by dyardyGIT** [comment] 2015-10-15 20:33
processResults and that code above iterates over the json response from the ajax call and builds an array of objects with the necessary properties id, text and data.   That seems fine.

As mentioned the issue seems to be after the selection of an item, on line 61 it sets the appropriate observable with the value selected, but whatever is next it is not able to set the UI element with the selected item 

How does that happen? hmm

**Comment by dyardyGIT** [comment] 2015-10-16 19:24
It errors on this (where dataBindingName=select2Data and $(element).select2("data") is the selected object 
`allBindings[dataBindingName]($(element).select2("data"));

There error occurs when $(element).select2("data") is an object.  If $(element).select2("data") is a string/integer i don't get any errors

**Comment by cruikshj** [comment] 2015-10-16 19:33
What do you have listening to the observable that expects only a value?  Perhaps all you need to do is make a computed property that extracts the value from the object provided by select2.

**Comment by dyardyGIT** [comment] 2015-10-16 19:35
Oddly, i do not see the above errors/issues if i move approver1 to the page, however if i put approver1 within the viewModel i do see the errors.

<select multiple="multiple" data-bind="select2Data: approver1, select2: spec" style="width:200px;"></select>

**Comment by cruikshj** [comment] 2015-10-16 19:41
Here is a jsfiddle for what I mean.  Feel free to change it to better represent your scenario

https://jsfiddle.net/jxfr2jy1/1/

**Comment by dyardyGIT** [comment] 2015-10-17 01:14
Well I was able to narrow down the issue. Crazy.  Hopefully you will have some insight.

I often use the following html snippet on the page to use while programming

`<pre data-bind="text: ko.toJSON($data, null, 2)"></pre> OR`
`<div data-bind="text: ko.toJSON(viewModel)"></div>`

If either of these are on the page I get a script error which makes the select2 fail to update.

With the first I had the error (as seen above)
`Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('checkbox') does not support selection.

With the second snipped i see this error
`Uncaught Error: Pass a function that returns the value of the ko.computed`

**Comment by cruikshj** [comment] 2015-10-17 02:02
I was able to repro.  

https://jsfiddle.net/jxfr2jy1/4/

`ko.toJSON` does not support DOM elements.  the select2 data object contains a variety of information, including the DOM element of the selected option.  The error is thrown because when the observable tied to select2data is updated, your debug binding is triggered and tries to write out that object.  

I am going to close this issue since the problem lies with attempting to render out the Select2 data object provided by Select2, and not with this binding handler.

**Closed by cruikshj** 2015-10-17 02:02 UTC
