### ISSUE TITLE
Text update delayed when more than one select2 references the same observable

### ISSUE THREAD

**Issue by quentinjones** [cruikshj/knockout-select2#8] opened 2016-02-23 22:34 UTC
I have an observable list and value bound to more than one select2 in different areas of my page. When I update selectA from itemA to itemB the text display of selectB doesn't change thought it appears the underlying value changed.  If I change selectA  to itemC the text display of selectB  updates to itemB.  Any idea what causes the delay, or how I could work around this?

**Comment by cruikshj** [comment] 2016-02-24 01:13
I will see if I can recreate in the lab.

**Comment by cruikshj** [comment] 2016-02-24 01:39
I committed a lab example of dual select2 boxes bound to the same data.  I don't see an issue in my very simple example.  Could you modify the sample in some way to reproduce?

**Comment by quentinjones** [comment] 2016-02-25 00:48
I tried to mess it up, but I couldn't reproduce the problem in the lab. I guess there's something going on in my application. I'll keep digging. Will update you if it's related.

**Comment by quentinjones** [comment] 2016-03-18 16:48
The problem was coming from using the select2 binding on the left side of my knockout bindings instead of the right. Apparently knockout evaluates them in that order.  I'm not quite sure why that caused a problem or if it's something that can be fixed, but all sorts of bad things start happening.

https://jsfiddle.net/hbrnctmh/1/

Theres also some flickering of the ui that seems to come from the setTimeout delay hack.

**Comment by cruikshj** [comment] 2016-03-21 18:23
Confirmed bug #11 

The "flickering" seems to be an artifact of jsfiddle. I could not recreate that issue locally.

Closing this issue as the bug will be tracked with the other issue.

**Closed by cruikshj** 2016-03-21 18:23 UTC
Labels: question
